### ISSUE TITLE
Validation issue for DataStream 2 - logStreamName field is not validated properly

### ISSUE THREAD

**Issue by amosstikal** [akamai/cli-property-manager#70] opened 2021-06-05 02:26 UTC
Hello,

I'm using rule format: v2020-11-02 and trying to configure DataStream 2 using Akamai Pipeline v0.7.6-RELEASE and getting validation error.

**The validation do pass using the Open API** (also approved by Akamai technical support), probably there is some issue in the CLI code

Also tried to uninstall and install again the CLI, but that didn't help

This is the command that I'm using:
akamai pipeline save -p my.pipeline dev

Here is the json snippet which fails to be validated:
...
{
            "name": "datastream",
            "options": {
                "streamType": "LOG",
                "logStreamTitle": "",
                "logEnabled": true,
                "logStreamName": 11135,
                "samplingPercentage": 100
            }
        }

Here is the validation error:
There are validation errors: 
 [
    {
        "location": {
            "template": "templates/main.json",
            "variables": [],
            "location": "rules/behaviors/8/options/logStreamName",
            "value": "11135"
        },
        "schemaLocation": "/definitions/catalog/behaviors/datastream/properties/options/properties/logStreamName",
        "detail": "instance type (string) does not match any allowed primitive type (allowed: [\"integer\",\"number\"])",
        "foundType": "string",
        "allowedTypes": [
            "integer",
            "number"
        ]
    }
]

When trying to reproduce, please try to run several times

This issue is "blocker" for using DataStream 2.0

Amos

**Comment by amosstikal** [comment] 2021-06-24 19:40
Hi,

After updating the CLI to version 0.7.7 the issue didn't occur again - I wonder if  version 0.7.7 had some related fix

**Comment by lkowalsk-akamai-com** [comment] 2022-05-27 13:49
Closing as the issue is not there any more.

**Closed by lkowalsk-akamai-com** 2022-05-27 13:49 UTC
